"use strict";
/**
 * Created by darryl on 2016-11-23.
 */

// ---- REQUIRES ---- //

// HTTP server using Express to handle incoming requests
let express = require('express');
let app = express();
let path = require('path');
let logger = require('morgan'); // helps log all requests
let cookieParser = require('cookie-parser'); // for handling cookies
let bodyParser = require('body-parser'); // for parsing request URL
let api = require('./app/chord_api').router;


// ---- SETUP ---- //

// set up logger and parsers
app.use(logger('dev')); // set up logger and parsers
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));
app.use(cookieParser("myTotallySecretSecret"));

// My ReST API
app.use('/api', api);

// Static route for client-side code generated by Angular
app.use('/',express.static(__dirname+'/../chord-sheet/dist'));
app.get('/*', function(req, res) {res.sendFile(path.join(__dirname+'/../chord-sheet/dist','index.html'))});

// Function to handle client errors
app.use(function(req, res, next) {
    let err = new Error('Not Found');
    err.status = 404;
    next(err);
});

// Base error handler
app.use(function (err, req, res, next) {
    console.error(err.stack);
    res.status(500).send('Something broke!');
    next();
});


// ---- START SERVER ---- //

app.listen(8080, function () {
    console.log('Server listening on port 8080!');
});


module.exports = app;